apiVersion: v1
kind: Secret
metadata:
  name: app-db-secrets
  namespace: default
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: ZW04MGFLOWd0dg==
  DATABASE: dG9kbw==

---

apiVersion: v1
kind: Secret
metadata:
  name: app-db-secrets
  namespace: stage-default
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: ZW04MGFLOWd0dg==
  DATABASE: ZGF0YWJhc2Vfc3RhZ2U=

---

apiVersion: v1
kind: Secret
metadata:
  name: app-db-secrets
  namespace: prod-default
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: ZW04MGFLOWd0dg==
  DATABASE: ZGF0YWJhc2VfcHJvZA==