apiVersion: v1
kind: Secret
metadata:
  name: docker-secrets
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXNXJkWE5vT1RnME5EcGtZMnR5WDNCaGRGOVpOa1pDT1RSMlRrazNNRkZ3TUU1RllXVnVlVTA1TFZGclNVMD0iCgkJfQoJfQp9 

---

apiVersion: v1
kind: Secret
metadata:
  name: docker-secrets
  namespace: stage-default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXNXJkWE5vT1RnME5EcGtZMnR5WDNCaGRGOVpOa1pDT1RSMlRrazNNRkZ3TUU1RllXVnVlVTA1TFZGclNVMD0iCgkJfQoJfQp9 
