apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: database
type: Opaque
data:
  POSTGRES_USER: dGVzdFVzZXIK
  POSTGRES_PASSWORD: dGVzdFVzZXJQYXNzd29yZAo=
  POSTGRES_DB: ZGF0YWJhc2U= 
